-- Module 5: Student Information Form — student_profiles table
CREATE TABLE IF NOT EXISTS student_profiles (
  id                    INT AUTO_INCREMENT PRIMARY KEY,
  student_id            INT NOT NULL,

  -- Section 1: Personal
  blood_group           VARCHAR(5)   NULL,
  mother_tongue         VARCHAR(100) NULL,
  religion              VARCHAR(100) NULL,
  caste                 VARCHAR(100) NULL,
  caste_category        ENUM('OC','OBC','BC','MBC','SC','ST','Others') NULL,
  sub_caste             VARCHAR(100) NULL,
  nationality           VARCHAR(100) NULL DEFAULT 'Indian',
  place_of_birth        VARCHAR(150) NULL,
  aadhaar_number        VARCHAR(12)  NULL,
  passport_photo_path   VARCHAR(255) NULL,
  student_email         VARCHAR(255) NULL,
  alternate_mobile      VARCHAR(15)  NULL,
  marital_status        ENUM('Single','Married','Other') NULL DEFAULT 'Single',
  physically_challenged TINYINT(1)   NOT NULL DEFAULT 0,
  disability_nature     VARCHAR(255) NULL,
  first_graduate        TINYINT(1)   NULL,
  annual_family_income  INT UNSIGNED NULL,

  -- Section 2: Address
  perm_address1         VARCHAR(255) NULL,
  perm_address2         VARCHAR(255) NULL,
  perm_city             VARCHAR(100) NULL,
  perm_taluk_id         INT          NULL,
  perm_district_id      INT          NULL,
  perm_state_id         INT          NULL,
  perm_pincode          CHAR(6)      NULL,
  comm_same_as_perm     TINYINT(1)   NOT NULL DEFAULT 0,
  comm_address1         VARCHAR(255) NULL,
  comm_address2         VARCHAR(255) NULL,
  comm_city             VARCHAR(100) NULL,
  comm_taluk_id         INT          NULL,
  comm_district_id      INT          NULL,
  comm_state_id         INT          NULL,
  comm_pincode          CHAR(6)      NULL,

  -- Section 3: Parent / Guardian
  family_situation      ENUM('both_parents','single_parent_father','single_parent_mother','guardian') NULL,
  father_name           VARCHAR(150) NULL,
  father_occupation     VARCHAR(150) NULL,
  father_qualification  VARCHAR(150) NULL,
  father_annual_income  INT UNSIGNED NULL,
  father_mobile         VARCHAR(15)  NULL,
  father_email          VARCHAR(255) NULL,
  mother_name           VARCHAR(150) NULL,
  mother_occupation     VARCHAR(150) NULL,
  mother_qualification  VARCHAR(150) NULL,
  mother_annual_income  INT UNSIGNED NULL,
  mother_mobile         VARCHAR(15)  NULL,
  mother_email          VARCHAR(255) NULL,
  guardian_name         VARCHAR(150) NULL,
  guardian_relationship VARCHAR(100) NULL,
  guardian_mobile       VARCHAR(15)  NULL,
  guardian_address      TEXT         NULL,
  guardian_email        VARCHAR(255) NULL,

  -- Section 4: Academic Background (JSON rows)
  qual_sslc             JSON         NULL,
  qual_hsc              JSON         NULL,
  qual_ug               JSON         NULL,
  qual_diploma          JSON         NULL,
  qual_other_1          JSON         NULL,
  qual_other_2          JSON         NULL,
  qual_sslc_doc_path    VARCHAR(255) NULL,
  qual_hsc_doc_path     VARCHAR(255) NULL,
  qual_ug_doc_path      VARCHAR(255) NULL,
  qual_diploma_doc_path VARCHAR(255) NULL,

  -- Section 5: Entrance & Admission
  admission_type        ENUM('management','government','nri','lateral_entry') NULL,
  entrance_exam_name    VARCHAR(150) NULL,
  entrance_hall_ticket  VARCHAR(100) NULL,
  entrance_rank_score   VARCHAR(50)  NULL,
  admission_number      VARCHAR(100) NULL,
  community_cert_number VARCHAR(100) NULL,
  community_cert_path   VARCHAR(255) NULL,
  transfer_cert_number  VARCHAR(100) NULL,
  transfer_cert_path    VARCHAR(255) NULL,
  conduct_cert_path     VARCHAR(255) NULL,
  migration_cert_path   VARCHAR(255) NULL,
  income_cert_path      VARCHAR(255) NULL,
  nativity_cert_path    VARCHAR(255) NULL,
  aadhaar_copy_path     VARCHAR(255) NULL,

  -- Section 6: Bank & Scholarship
  bank_account_holder   VARCHAR(150) NULL,
  bank_name             VARCHAR(150) NULL,
  bank_branch           VARCHAR(150) NULL,
  bank_account_number   VARCHAR(30)  NULL,
  bank_ifsc             CHAR(11)     NULL,
  bank_passbook_path    VARCHAR(255) NULL,
  scholarship_applied   TINYINT(1)   NULL DEFAULT 0,
  scholarship_scheme    VARCHAR(200) NULL,
  scholarship_app_number VARCHAR(100) NULL,

  -- Tracking
  form_completion_pct   TINYINT UNSIGNED NOT NULL DEFAULT 0,
  form_status           ENUM('incomplete','submitted') NOT NULL DEFAULT 'incomplete',
  form_submitted_at     DATETIME     NULL,
  last_saved_at         DATETIME     NULL,
  created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP    NULL ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uq_student_profiles_student (student_id),
  KEY idx_student_profiles_status (form_status),

  CONSTRAINT fk_sp_student      FOREIGN KEY (student_id)       REFERENCES students(id),
  CONSTRAINT fk_sp_perm_taluk   FOREIGN KEY (perm_taluk_id)    REFERENCES taluks(id),
  CONSTRAINT fk_sp_perm_dist    FOREIGN KEY (perm_district_id) REFERENCES districts(id),
  CONSTRAINT fk_sp_perm_state   FOREIGN KEY (perm_state_id)    REFERENCES states(id),
  CONSTRAINT fk_sp_comm_taluk   FOREIGN KEY (comm_taluk_id)    REFERENCES taluks(id),
  CONSTRAINT fk_sp_comm_dist    FOREIGN KEY (comm_district_id) REFERENCES districts(id),
  CONSTRAINT fk_sp_comm_state   FOREIGN KEY (comm_state_id)    REFERENCES states(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
