<?php
use App\Helpers\View;
use App\Helpers\Csrf;
$title = 'Batch #' . View::e($batch['id']) . ' — Enrolment Numbers';

$statusBadge = [
    'pending'     => 'warning',
    'in_progress' => 'info',
    'approved'    => 'success',
];
$statusLabel = [
    'pending'     => 'Pending',
    'in_progress' => 'In Progress',
    'approved'    => 'Approved',
];
$canApprove = in_array($role, ['dept_admin', 'institution_admin'], true);
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h4 class="mb-0">Enrolment Batch #<?= View::e($batch['id']) ?></h4>
    <a href="/enrolment" class="btn btn-outline-secondary btn-sm">← Back to Batches</a>
</div>

<?php if (!empty($_SESSION['flash'])): $f = $_SESSION['flash']; unset($_SESSION['flash']); ?>
    <div class="alert alert-<?= View::e($f['type']) ?> alert-dismissible fade show" role="alert">
        <?= View::e($f['message']) ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<?php endif; ?>

<!-- Batch summary card -->
<div class="card shadow-sm mb-4">
    <div class="card-body">
        <div class="row g-3">
            <div class="col-sm-6 col-md-3">
                <div class="text-muted small">Department</div>
                <div class="fw-semibold"><?= View::e($batch['dept_name']) ?> (<?= View::e($batch['dept_code']) ?>)</div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="text-muted small">Academic Year</div>
                <div class="fw-semibold"><?= View::e($batch['ay_display']) ?></div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="text-muted small">Student Count</div>
                <div class="fw-semibold"><?= View::e($batch['student_count']) ?></div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="text-muted small">Status</div>
                <div>
                    <span class="badge bg-<?= View::e($statusBadge[$status] ?? 'secondary') ?> fs-6">
                        <?= View::e($statusLabel[$status] ?? $status) ?>
                    </span>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="text-muted small">Generated By</div>
                <div class="fw-semibold"><?= View::e($batch['generated_by_name']) ?></div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="text-muted small">Generated At</div>
                <div class="fw-semibold"><?= View::e($batch['created_at']) ?></div>
            </div>
        </div>
    </div>
</div>

<!-- Search & filter -->
<form method="GET" action="/enrolment/batch/<?= View::e($batch['id']) ?>" class="card shadow-sm mb-4">
    <div class="card-body">
        <div class="row g-2 align-items-end">
            <div class="col-md-5">
                <label class="form-label mb-1 small fw-semibold">Search</label>
                <input type="text" name="search" class="form-control form-control-sm"
                       placeholder="Name or mobile…"
                       value="<?= View::e($filters['search'] ?? '') ?>">
            </div>
            <div class="col-md-4">
                <label class="form-label mb-1 small fw-semibold">Approval Status</label>
                <select name="enrolment_approval_status" class="form-select form-select-sm">
                    <option value="">All</option>
                    <option value="pending"  <?= (($filters['enrolment_approval_status'] ?? '') === 'pending')  ? 'selected' : '' ?>>Pending</option>
                    <option value="approved" <?= (($filters['enrolment_approval_status'] ?? '') === 'approved') ? 'selected' : '' ?>>Approved</option>
                </select>
            </div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-primary btn-sm w-100">Filter</button>
            </div>
        </div>
    </div>
</form>

<!-- Approve All modal trigger + form -->
<?php if ($canApprove && $status !== 'approved'): ?>
<div class="d-flex gap-2 mb-3">
    <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#approveAllModal">
        Approve All Pending
    </button>
    <button type="button" id="approveSelectedBtn" class="btn btn-outline-success btn-sm" disabled
            data-bs-toggle="modal" data-bs-target="#approveSelectedModal">
        Approve Selected (<span id="selectedCount">0</span>)
    </button>
</div>
<?php endif; ?>

<!-- Student table -->
<div class="card shadow-sm">
    <div class="card-body p-0">
        <form id="selectedForm" method="POST" action="/enrolment/batch/<?= View::e($batch['id']) ?>/approve-selected">
            <?= Csrf::field() ?>
            <div class="table-responsive">
                <table class="table table-hover table-sm mb-0">
                    <thead class="table-light">
                        <tr>
                            <?php if ($canApprove && $status !== 'approved'): ?>
                            <th style="width:40px;">
                                <input type="checkbox" id="selectAll" class="form-check-input" title="Select all pending">
                            </th>
                            <?php endif; ?>
                            <th>S.No</th>
                            <th>Name</th>
                            <th>Mobile</th>
                            <th>Class</th>
                            <th>Section</th>
                            <th>Enrolment Number</th>
                            <th>Status</th>
                            <th>Approved By</th>
                            <th>Approved At</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (empty($students)): ?>
                        <tr>
                            <td colspan="<?= $canApprove && $status !== 'approved' ? 10 : 9 ?>" class="text-center text-muted py-4">
                                No students found.
                            </td>
                        </tr>
                        <?php else: ?>
                        <?php foreach ($students as $s): ?>
                        <tr>
                            <?php if ($canApprove && $status !== 'approved'): ?>
                            <td>
                                <?php if ($s['enrolment_approval_status'] === 'pending'): ?>
                                <input type="checkbox" name="student_ids[]"
                                       value="<?= View::e($s['id']) ?>"
                                       class="form-check-input student-checkbox">
                                <?php else: ?>
                                <input type="checkbox" class="form-check-input" disabled>
                                <?php endif; ?>
                            </td>
                            <?php endif; ?>
                            <td><?= View::e($s['enrolment_serial']) ?></td>
                            <td><?= View::e($s['first_name'] . ' ' . $s['last_name']) ?></td>
                            <td><?= View::e($s['mobile']) ?></td>
                            <td><?= View::e($s['class_display'] ?? '—') ?></td>
                            <td><?= View::e($s['section_display'] ?? '—') ?></td>
                            <td>
                                <code><?= View::e($s['enrolment_number']) ?></code>
                            </td>
                            <td>
                                <?php
                                $st = $s['enrolment_approval_status'] ?? '';
                                $stBadge = ($st === 'approved') ? 'success' : 'warning';
                                $stLabel = ($st === 'approved') ? 'Approved' : 'Pending';
                                ?>
                                <span class="badge bg-<?= $stBadge ?>"><?= $stLabel ?></span>
                            </td>
                            <td><?= View::e($s['approved_by_name'] ?? '—') ?></td>
                            <td><?= View::e($s['enrolment_approved_at'] ?? '—') ?></td>
                        </tr>
                        <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

<!-- Pagination -->
<?php if ($pages > 1): ?>
<nav class="mt-3">
    <ul class="pagination pagination-sm">
        <?php for ($p = 1; $p <= $pages; $p++): ?>
        <li class="page-item <?= ($p === $page) ? 'active' : '' ?>">
            <a class="page-link" href="?page=<?= $p ?>&search=<?= urlencode($filters['search'] ?? '') ?>&enrolment_approval_status=<?= urlencode($filters['enrolment_approval_status'] ?? '') ?>">
                <?= $p ?>
            </a>
        </li>
        <?php endfor; ?>
    </ul>
</nav>
<?php endif; ?>

<!-- Approve All Modal -->
<?php if ($canApprove && $status !== 'approved'): ?>
<div class="modal fade" id="approveAllModal" tabindex="-1" aria-labelledby="approveAllModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="approveAllModalLabel">Approve All Pending Numbers</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>This will approve <strong>all pending</strong> enrolment numbers in this batch.
                Students will immediately be able to see their enrolment numbers. This action cannot be undone.</p>
                <p class="text-muted mb-0">Batch: <strong>#<?= View::e($batch['id']) ?></strong> — <?= View::e($batch['dept_name']) ?>, <?= View::e($batch['ay_display']) ?></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form method="POST" action="/enrolment/batch/<?= View::e($batch['id']) ?>/approve-all" class="d-inline">
                    <?= Csrf::field() ?>
                    <button type="submit" class="btn btn-success">Yes, Approve All</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Approve Selected Modal -->
<div class="modal fade" id="approveSelectedModal" tabindex="-1" aria-labelledby="approveSelectedModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="approveSelectedModalLabel">Approve Selected Numbers</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>This will approve the <strong><span id="modalSelectedCount">0</span> selected</strong>
                enrolment numbers. Those students will immediately be able to see their enrolment numbers.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="confirmSelectedBtn">Yes, Approve Selected</button>
            </div>
        </div>
    </div>
</div>

<script>
(function () {
    const selectAll  = document.getElementById('selectAll');
    const checkboxes = document.querySelectorAll('.student-checkbox');
    const countSpan  = document.getElementById('selectedCount');
    const modalCount = document.getElementById('modalSelectedCount');
    const approveBtn = document.getElementById('approveSelectedBtn');
    const form       = document.getElementById('selectedForm');
    const confirmBtn = document.getElementById('confirmSelectedBtn');

    function updateCount() {
        const checked = document.querySelectorAll('.student-checkbox:checked').length;
        countSpan.textContent  = checked;
        modalCount.textContent = checked;
        approveBtn.disabled    = checked === 0;
    }

    if (selectAll) {
        selectAll.addEventListener('change', function () {
            checkboxes.forEach(function (cb) { cb.checked = selectAll.checked; });
            updateCount();
        });
    }

    checkboxes.forEach(function (cb) {
        cb.addEventListener('change', updateCount);
    });

    if (confirmBtn) {
        confirmBtn.addEventListener('click', function () {
            form.submit();
        });
    }
})();
</script>
<?php endif; ?>
