<?php
use App\Helpers\View;
use App\Helpers\Csrf;
$title = 'Enrolment Batches';

$statusBadge = [
    'pending'     => 'warning',
    'in_progress' => 'info',
    'approved'    => 'success',
];
$statusLabel = [
    'pending'     => 'Pending',
    'in_progress' => 'In Progress',
    'approved'    => 'Approved',
];
$currentAy    = (int)($_GET['academic_year_id'] ?? 0);
$currentDept  = (int)($_GET['department_id']    ?? 0);
$currentStatus = $_GET['status'] ?? '';
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h4 class="mb-0">Enrolment Batches</h4>
    <?php if (in_array($role, ['staff', 'dept_admin'], true)): ?>
    <a href="/enrolment/generate" class="btn btn-primary btn-sm">+ Generate New Batch</a>
    <?php endif; ?>
</div>

<?php if (!empty($_SESSION['flash'])): $f = $_SESSION['flash']; unset($_SESSION['flash']); ?>
    <div class="alert alert-<?= View::e($f['type']) ?> alert-dismissible fade show" role="alert">
        <?= View::e($f['message']) ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<?php endif; ?>

<!-- Filters -->
<form method="GET" action="/enrolment" class="card shadow-sm mb-4">
    <div class="card-body">
        <div class="row g-2 align-items-end">
            <div class="col-md-4">
                <label class="form-label mb-1 small fw-semibold">Academic Year</label>
                <select name="academic_year_id" class="form-select form-select-sm">
                    <option value="">All Years</option>
                    <?php foreach ($academicYears as $ay): ?>
                        <option value="<?= View::e($ay['id']) ?>" <?= ($currentAy === (int)$ay['id']) ? 'selected' : '' ?>>
                            <?= View::e($ay['display']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php if ($role === 'institution_admin'): ?>
            <div class="col-md-4">
                <label class="form-label mb-1 small fw-semibold">Department</label>
                <select name="department_id" class="form-select form-select-sm">
                    <option value="">All Departments</option>
                    <?php foreach ($departments as $d): ?>
                        <option value="<?= View::e($d['id']) ?>" <?= ($currentDept === (int)$d['id']) ? 'selected' : '' ?>>
                            <?= View::e($d['name']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php endif; ?>
            <div class="col-md-3">
                <label class="form-label mb-1 small fw-semibold">Status</label>
                <select name="status" class="form-select form-select-sm">
                    <option value="">All Statuses</option>
                    <option value="pending"     <?= ($currentStatus === 'pending')     ? 'selected' : '' ?>>Pending</option>
                    <option value="in_progress" <?= ($currentStatus === 'in_progress') ? 'selected' : '' ?>>In Progress</option>
                    <option value="approved"    <?= ($currentStatus === 'approved')    ? 'selected' : '' ?>>Approved</option>
                </select>
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary btn-sm w-100">Filter</button>
            </div>
        </div>
    </div>
</form>

<!-- Batch table -->
<div class="card shadow-sm">
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover table-sm mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Batch ID</th>
                        <th>Academic Year</th>
                        <?php if ($role === 'institution_admin'): ?>
                        <th>Department</th>
                        <?php endif; ?>
                        <th class="text-end">Total</th>
                        <th class="text-end">Approved</th>
                        <th class="text-end">Pending</th>
                        <th>Status</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($batches)): ?>
                    <tr>
                        <td colspan="<?= ($role === 'institution_admin') ? 10 : 9 ?>" class="text-center text-muted py-4">
                            No batches found. <?php if (in_array($role, ['staff', 'dept_admin'], true)): ?>
                            <a href="/enrolment/generate">Generate the first batch.</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php else: ?>
                    <?php foreach ($batches as $b):
                        // Client-side status filter (derived_status not filterable in SQL easily)
                        if ($currentStatus && ($b['derived_status'] ?? '') !== $currentStatus) continue;
                    ?>
                    <tr>
                        <td>#<?= View::e($b['id']) ?></td>
                        <td><?= View::e($b['ay_display']) ?></td>
                        <?php if ($role === 'institution_admin'): ?>
                        <td><?= View::e($b['dept_name']) ?> (<?= View::e($b['dept_code']) ?>)</td>
                        <?php endif; ?>
                        <td class="text-end"><?= View::e($b['student_count']) ?></td>
                        <td class="text-end text-success"><?= View::e((int)($b['approved_count'] ?? 0)) ?></td>
                        <td class="text-end text-warning"><?= View::e((int)($b['pending_count']  ?? 0)) ?></td>
                        <td>
                            <?php $ds = $b['derived_status'] ?? 'pending'; ?>
                            <span class="badge bg-<?= View::e($statusBadge[$ds] ?? 'secondary') ?>">
                                <?= View::e($statusLabel[$ds] ?? $ds) ?>
                            </span>
                        </td>
                        <td><?= View::e($b['generated_by_name']) ?></td>
                        <td><?= View::e($b['created_at']) ?></td>
                        <td>
                            <a href="/enrolment/batch/<?= View::e($b['id']) ?>" class="btn btn-outline-primary btn-sm">
                                View
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php if ($role === 'institution_admin'): ?>
<div class="mt-3">
    <a href="/enrolment/summary" class="btn btn-outline-secondary btn-sm">View Department Summary</a>
</div>
<?php endif; ?>
